### ISSUE TITLE
WARN deprecated core-js@2.6.12

### ISSUE THREAD

**Issue by jyeatman** [yeatmanlab/create-roar-app#6] opened 2022-10-19 18:53 UTC
Need to install the following packages:
  create-roar-app@2.0.0
Ok to proceed? (y) y
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

**Comment by richford** [comment] 2022-10-21 18:24
I believe this should be fixed in [2.1.2](https://github.com/yeatmanlab/create-roar-app/commit/2da9b9b14a92a7d84e939e2fd59e8838f87d9082).

I couldn't reproduce with the latest version.

@jyeatman, can you try a clean install with
```
npx create-roar-app@latest test-roar-outdated-dependencies
```

And then you are free to delete the resulting `test-roar-outdated-dependencies` folder.

**Comment by richford** [comment] 2022-10-24 15:32
Declaring victory here. But feel free to reopen the issue if it persists.

**Closed as completed by richford** 2022-10-24 15:32 UTC
